<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title>Chyba 404</title>
        <link rel="stylesheet" href="styly.css" type="text/css"/>
    </head>

    <body>
        <div class="menu">
        <header>
           
        </header>
        
            <?php include __DIR__ . '/menu.phtml'; ?>
        </div>
<div class="obsah">
            <article> 
                 <h1>Chyba 404</h1>
                <p>Požadovaná stránka nebyla nalezena, zkontrolujte prosím URL adresu</p>
            </article>
        </div>
        <footer>
            <p> 
                <?php include __DIR__ . '/paticka.phtml'; ?>
            </p>
        </footer>
    </body>
</html>


