<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title>Chyba 500</title>
        <link rel="stylesheet" href="styly.css" type="text/css"/>
    </head>

    <body>
        <div class="menu">     
            <?php include __DIR__ . '/menu.phtml'; ?>
        </div>
        <div class="obsah">
            <h1>Chyba 500</h1>
            <article>

                <p>Stránka má chybu!</p>
            </article>
        </div>
        <footer>
            <p> 
                <?php include __DIR__ . '/paticka.phtml'; ?>
            </p>
        </footer>
    </body>
</html>